# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
    image: yegor256/rultor-image:1.13.0
assets:
    pat.txt: yegor256/objectionary-secrets#azure-devops-pat.txt
install: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
    source ~/.bashrc
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm install 16
    npm install -g vsce
release:
    script: |-
        [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
        npm version ${tag} --no-git-tag-version
        npm install
        npm run convert-yaml && npm run vscode:prepublish
        cat ../pat.txt | vsce login eolang
        vsce publish
merge:
    script: |-
        npm install
        npm run convert-yaml && npm run vscode:prepublish
